# Generated by Django 4.2.9 on 2025-03-05 21:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-99.99')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='ROI Totale'),
        ),
    ]
