# Generated by Django 4.2.9 on 2025-03-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_total_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Comune/Regione'),
        ),
    ]
