# Generated by Django 4.2.9 on 2025-03-05 22:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-99.99')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='ROI'),
        ),
    ]
