# Generated by Django 4.2.9 on 2025-03-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_subproject_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indirizzo'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='latitude_approved',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine Approvata'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='latitude_proposed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine Proposta'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='longitude_approved',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine Approvata'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='longitude_proposed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine Proposta'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Stazione'),
        ),
    ]
