# Generated by Django 4.2.9 on 2025-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_subproject_charger_brand_subproject_charger_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='local_festival_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Giorni Festa Locale/Anno'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='rainy_days',
            field=models.PositiveSmallIntegerField(default=0, help_text="Giorni di pioggia stimati che riducono l'utilizzo delle colonnine", verbose_name='Giorni di Pioggia Previsti/Anno'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='weekly_market_day',
            field=models.CharField(blank=True, choices=[('', '-- Nessuno --'), ('monday', 'Lunedì'), ('tuesday', 'Martedì'), ('wednesday', 'Mercoledì'), ('thursday', 'Giovedì'), ('friday', 'Venerdì'), ('saturday', 'Sabato'), ('sunday', 'Domenica')], max_length=10, null=True, verbose_name='Giorno Mercato Settimanale'),
        ),
    ]
