# Generated by Django 4.2.9 on 2025-03-08 22:37

import cpo_planner.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('file', models.FileField(upload_to=cpo_planner.documents.models.document_upload_path, verbose_name='File')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('pending', 'In Attesa di Approvazione'), ('approved', 'Approvato'), ('rejected', 'Respinto'), ('expired', 'Scaduto')], default='draft', max_length=20, verbose_name='Stato')),
                ('object_id', models.PositiveIntegerField()),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Versione')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data di Emissione')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data di Scadenza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria Documento',
                'verbose_name_plural': 'Categorie Documenti',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('file', models.FileField(upload_to='document_templates/', verbose_name='File Template')),
                ('document_type', models.CharField(max_length=100, verbose_name='Tipo Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
            ],
            options={
                'verbose_name': 'Template Documento',
                'verbose_name_plural': 'Template Documenti',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('in_progress', 'In lavorazione'), ('completed', 'Completato'), ('cancelled', 'Annullato')], default='pending', max_length=20, verbose_name='Stato')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Scadenza')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_document_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assegnato a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Attività Documento',
                'verbose_name_plural': 'Attività Documenti',
                'ordering': ['due_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Testo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_notes', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Nota Documento',
                'verbose_name_plural': 'Note Documento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document', to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
    ]
