# Generated by Django 5.0.7 on 2025-03-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Progetto')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data di inizio')),
                ('estimated_completion_date', models.DateField(blank=True, null=True, verbose_name='Data di completamento stimata')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Data di completamento effettiva')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budget totale (€)')),
                ('status', models.CharField(choices=[('planning', 'Pianificazione'), ('approval', 'Approvazione'), ('installation', 'Installazione'), ('testing', 'Collaudo'), ('operational', 'Operativo')], default='planning', max_length=20, verbose_name='Stato')),
            ],
            options={
                'verbose_name': 'Progetto di ricarica',
                'verbose_name_plural': 'Progetti di ricarica',
                'ordering': ['municipality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Comune')),
                ('province', models.CharField(max_length=2, verbose_name='Provincia')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Popolazione')),
                ('ev_adoption_rate', models.FloatField(default=2.0, verbose_name='Tasso di adozione EV (%)')),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'ordering': ['name', 'province'],
            },
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codice identificativo')),
                ('location', models.CharField(max_length=255, verbose_name='Indirizzo')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitudine')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitudine')),
                ('connection_type', models.CharField(choices=[('ac', 'AC - Corrente Alternata'), ('dc', 'DC - Corrente Continua'), ('hybrid', 'Ibrido AC/DC')], max_length=10, verbose_name='Tipo di connessione')),
                ('max_power', models.FloatField(verbose_name='Potenza massima (kW)')),
                ('num_connectors', models.IntegerField(default=2, verbose_name='Numero di connettori')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Costo d'acquisto (€)")),
                ('installation_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Costo d'installazione (€)")),
                ('connection_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo di allaccio (€)')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Data di installazione')),
                ('active_date', models.DateField(blank=True, null=True, verbose_name='Data di attivazione')),
                ('status', models.CharField(choices=[('planned', 'Pianificata'), ('ordered', 'Ordinata'), ('installed', 'Installata'), ('active', 'Attiva'), ('maintenance', 'In manutenzione'), ('disabled', 'Disattivata')], default='planned', max_length=20, verbose_name='Stato')),
                ('has_pv_system', models.BooleanField(default=False, verbose_name='Integrazione fotovoltaico')),
                ('pv_power', models.FloatField(blank=True, null=True, verbose_name='Potenza fotovoltaico (kWp)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_stations', to='infrastructure.chargingproject', verbose_name='Progetto')),
            ],
            options={
                'verbose_name': 'Stazione di ricarica',
                'verbose_name_plural': 'Stazioni di ricarica',
                'ordering': ['project', 'code'],
            },
        ),
        migrations.AddField(
            model_name='chargingproject',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_projects', to='infrastructure.municipality', verbose_name='Comune'),
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome attività')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('planned_start_date', models.DateField(verbose_name='Data di inizio pianificata')),
                ('planned_end_date', models.DateField(verbose_name='Data di fine pianificata')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Data di inizio effettiva')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Data di fine effettiva')),
                ('priority', models.CharField(choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Priorità')),
                ('status', models.CharField(choices=[('not_started', 'Non iniziata'), ('in_progress', 'In corso'), ('completed', 'Completata'), ('delayed', 'In ritardo'), ('cancelled', 'Annullata')], default='not_started', max_length=20, verbose_name='Stato')),
                ('responsible', models.CharField(blank=True, max_length=100, verbose_name='Responsabile')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_tasks', to='infrastructure.projecttask', verbose_name='Dipendenze')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='infrastructure.chargingproject', verbose_name='Progetto')),
            ],
            options={
                'verbose_name': 'Attività di progetto',
                'verbose_name_plural': 'Attività di progetto',
                'ordering': ['planned_start_date', 'planned_end_date'],
            },
        ),
    ]
