# Generated by Django 4.2.9 on 2025-03-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_municipality_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome template')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modello')),
                ('connection_type', models.CharField(choices=[('ac', 'AC - Corrente Alternata'), ('dc', 'DC - Corrente Continua'), ('hybrid', 'Ibrido AC/DC')], max_length=10, verbose_name='Tipo di connessione')),
                ('power_kw', models.FloatField(verbose_name='Potenza (kW)')),
                ('num_connectors', models.IntegerField(default=2, verbose_name='Numero di connettori')),
                ('connector_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('chademo', 'CHAdeMO'), ('ccs', 'CCS'), ('tesla', 'Tesla'), ('multiple', 'Multipli')], default='type2', max_length=10, verbose_name='Tipo di connettore')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Costo d'acquisto (€)")),
                ('installation_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Costo d'installazione standard (€)")),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo manutenzione annuale (€)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Dimensioni')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('protection_rating', models.CharField(blank=True, max_length=10, verbose_name='Grado di protezione IP')),
                ('has_display', models.BooleanField(default=True, verbose_name='Display')),
                ('has_rfid', models.BooleanField(default=True, verbose_name='Lettore RFID')),
                ('has_app_control', models.BooleanField(default=True, verbose_name='Controllo da app')),
                ('has_lan', models.BooleanField(default=True, verbose_name='Connessione LAN')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Connessione WiFi')),
                ('has_4g', models.BooleanField(default=False, verbose_name='Connessione 4G')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('technical_specs', models.TextField(blank=True, verbose_name='Specifiche tecniche')),
                ('image', models.ImageField(blank=True, null=True, upload_to='station_templates/', verbose_name='Immagine')),
            ],
            options={
                'verbose_name': 'Template stazione di ricarica',
                'verbose_name_plural': 'Template stazioni di ricarica',
                'ordering': ['brand', 'model', 'power_kw'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome tariffa')),
                ('provider', models.CharField(max_length=100, verbose_name='Fornitore')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('cost_tier1', models.DecimalField(decimal_places=4, default=0.25, max_digits=6, verbose_name='Costo €/kWh (≤ 7kW)')),
                ('cost_tier2', models.DecimalField(decimal_places=4, default=0.3, max_digits=6, verbose_name='Costo €/kWh (≤ 22kW)')),
                ('cost_tier3', models.DecimalField(decimal_places=4, default=0.35, max_digits=6, verbose_name='Costo €/kWh (≤ 50kW)')),
                ('cost_tier4', models.DecimalField(decimal_places=4, default=0.4, max_digits=6, verbose_name='Costo €/kWh (≤ 150kW)')),
                ('cost_tier5', models.DecimalField(decimal_places=4, default=0.45, max_digits=6, verbose_name='Costo €/kWh (> 150kW)')),
                ('connection_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Costo fisso di connessione (€/mese)')),
                ('power_fee', models.DecimalField(decimal_places=2, default=1.5, max_digits=6, verbose_name='Costo potenza impegnata (€/kW/mese)')),
                ('valid_from', models.DateField(verbose_name='Valido dal')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valido fino al')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Tariffa elettrica',
                'verbose_name_plural': 'Tariffe elettriche',
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManagementFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome configurazione')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('session_fee', models.DecimalField(decimal_places=2, default=0.5, max_digits=6, verbose_name='Commissione fissa per sessione (€)')),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Commissione percentuale (%)')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=20.0, max_digits=8, verbose_name='Canone mensile (€)')),
                ('customer_price_tier1', models.DecimalField(decimal_places=4, default=0.4, max_digits=6, verbose_name='Prezzo cliente €/kWh (≤ 7kW)')),
                ('customer_price_tier2', models.DecimalField(decimal_places=4, default=0.5, max_digits=6, verbose_name='Prezzo cliente €/kWh (≤ 22kW)')),
                ('customer_price_tier3', models.DecimalField(decimal_places=4, default=0.6, max_digits=6, verbose_name='Prezzo cliente €/kWh (≤ 50kW)')),
                ('customer_price_tier4', models.DecimalField(decimal_places=4, default=0.7, max_digits=6, verbose_name='Prezzo cliente €/kWh (≤ 150kW)')),
                ('customer_price_tier5', models.DecimalField(decimal_places=4, default=0.8, max_digits=6, verbose_name='Prezzo cliente €/kWh (> 150kW)')),
                ('valid_from', models.DateField(verbose_name='Valido dal')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valido fino al')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Configurazione tariffaria',
                'verbose_name_plural': 'Configurazioni tariffarie',
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StationUsageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome profilo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('weekday_morning_usage', models.IntegerField(default=30, verbose_name='Utilizzo feriale mattina (%)')),
                ('weekday_afternoon_usage', models.IntegerField(default=50, verbose_name='Utilizzo feriale pomeriggio (%)')),
                ('weekday_evening_usage', models.IntegerField(default=20, verbose_name='Utilizzo feriale sera (%)')),
                ('weekend_morning_usage', models.IntegerField(default=40, verbose_name='Utilizzo weekend mattina (%)')),
                ('weekend_afternoon_usage', models.IntegerField(default=60, verbose_name='Utilizzo weekend pomeriggio (%)')),
                ('weekend_evening_usage', models.IntegerField(default=30, verbose_name='Utilizzo weekend sera (%)')),
                ('customer_profile', models.CharField(choices=[('commuter', 'Pendolari'), ('resident', 'Residenti'), ('visitor', 'Visitatori'), ('business', 'Aziende'), ('mixed', 'Misto')], default='mixed', max_length=20, verbose_name='Profilo cliente')),
                ('avg_session_duration', models.IntegerField(default=45, verbose_name='Durata media sessione (min)')),
                ('avg_energy_per_session', models.DecimalField(decimal_places=2, default=15.0, max_digits=6, verbose_name='Energia media per sessione (kWh)')),
                ('avg_daily_sessions', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Sessioni giornaliere medie')),
            ],
            options={
                'verbose_name': 'Profilo di utilizzo',
                'verbose_name_plural': 'Profili di utilizzo',
            },
        ),
    ]
