# Generated by Django 4.2.9 on 2025-03-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_chargingstationtemplate_ground_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='ground_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area occupata sul terreno in mq, utile per il calcolo della tassa di occupazione', max_digits=6, null=True, verbose_name='Superficie occupata (mq)'),
        ),
    ]
