# Generated by Django 4.2.9 on 2025-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_chargingstation_ground_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='modem_4g_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo aggiuntivo per il modem 4G se richiesto', max_digits=8, verbose_name='Costo modem 4G (€)'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='sim_annual_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo annuale per la SIM dati se richiesta', max_digits=8, verbose_name='Costo annuale SIM dati (€)'),
        ),
        migrations.AddField(
            model_name='chargingstationtemplate',
            name='modem_4g_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo aggiuntivo per il modem 4G se richiesto', max_digits=8, verbose_name='Costo modem 4G (€)'),
        ),
        migrations.AddField(
            model_name='chargingstationtemplate',
            name='sim_annual_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo annuale per la SIM dati se richiesta', max_digits=8, verbose_name='Costo annuale SIM dati (€)'),
        ),
    ]
