# Generated by Django 4.2.9 on 2025-03-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_chargingstation_modem_4g_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100, verbose_name='Nome configurazione')),
                ('is_active', models.BooleanField(default=True, verbose_name='Configurazione attiva')),
                ('sim_data_cost_monthly', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Costo mensile SIM dati (€)')),
                ('modem_4g_cost', models.DecimalField(decimal_places=2, default=150.0, max_digits=8, verbose_name='Costo modem 4G (€)')),
                ('default_energy_cost', models.DecimalField(decimal_places=4, default=0.25, max_digits=6, verbose_name='Costo energia predefinito (€/kWh)')),
                ('default_energy_price', models.DecimalField(decimal_places=4, default=0.45, max_digits=6, verbose_name='Prezzo ricarica predefinito (€/kWh)')),
                ('insurance_cost_per_station', models.DecimalField(decimal_places=2, default=200.0, max_digits=8, verbose_name='Costo assicurazione per stazione (€/anno)')),
                ('maintenance_cost_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentuale del costo di acquisto per la manutenzione annuale', max_digits=5, verbose_name='Percentuale costo manutenzione annuale')),
                ('public_land_fee_per_sqm', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Tassa occupazione suolo pubblico (€/mq/anno)')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=22.0, max_digits=5, verbose_name='Percentuale IVA')),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name="Tasso d'inflazione annuale (%)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni Globali',
                'verbose_name_plural': 'Impostazioni Globali',
            },
        ),
    ]
