# Generated by Django 4.2.9 on 2025-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_electricitytariff_pun_fee_f1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitytariff',
            name='pun_fee_f1',
            field=models.DecimalField(decimal_places=4, default=0.02, help_text='Costo aggiuntivo rispetto al PUN per fascia F1', max_digits=6, verbose_name='Commissione su PUN F1 (€/kWh)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='pun_fee_f2',
            field=models.DecimalField(decimal_places=4, default=0.02, help_text='Costo aggiuntivo rispetto al PUN per fascia F2', max_digits=6, verbose_name='Commissione su PUN F2 (€/kWh)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='pun_fee_f3',
            field=models.DecimalField(decimal_places=4, default=0.02, help_text='Costo aggiuntivo rispetto al PUN per fascia F3', max_digits=6, verbose_name='Commissione su PUN F3 (€/kWh)'),
        ),
    ]
