# Generated by Django 4.2.9 on 2025-03-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_alter_electricitytariff_pun_fee_f1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitytariff',
            name='cost_tier1',
            field=models.DecimalField(decimal_places=4, default=0.25, help_text='Solo per tariffe a prezzo fisso', max_digits=6, verbose_name='Costo €/kWh (≤ 7kW)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='cost_tier2',
            field=models.DecimalField(decimal_places=4, default=0.3, help_text='Solo per tariffe a prezzo fisso', max_digits=6, verbose_name='Costo €/kWh (≤ 22kW)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='cost_tier3',
            field=models.DecimalField(decimal_places=4, default=0.35, help_text='Solo per tariffe a prezzo fisso', max_digits=6, verbose_name='Costo €/kWh (≤ 50kW)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='cost_tier4',
            field=models.DecimalField(decimal_places=4, default=0.4, help_text='Solo per tariffe a prezzo fisso', max_digits=6, verbose_name='Costo €/kWh (≤ 150kW)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='cost_tier5',
            field=models.DecimalField(decimal_places=4, default=0.45, help_text='Solo per tariffe a prezzo fisso', max_digits=6, verbose_name='Costo €/kWh (> 150kW)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='pun_fee_f1',
            field=models.DecimalField(decimal_places=4, default=0.02, help_text='Commissione aggiuntiva rispetto al PUN per fascia F1 (ore di punta: Lun-Ven 8-19)', max_digits=6, verbose_name='Commissione su PUN F1 (€/kWh)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='pun_fee_f2',
            field=models.DecimalField(decimal_places=4, default=0.02, help_text='Commissione aggiuntiva rispetto al PUN per fascia F2 (ore intermedie: Lun-Ven 7-8/19-23, Sab 7-23)', max_digits=6, verbose_name='Commissione su PUN F2 (€/kWh)'),
        ),
        migrations.AlterField(
            model_name='electricitytariff',
            name='pun_fee_f3',
            field=models.DecimalField(decimal_places=4, default=0.02, help_text='Commissione aggiuntiva rispetto al PUN per fascia F3 (notti, domeniche e festivi)', max_digits=6, verbose_name='Commissione su PUN F3 (€/kWh)'),
        ),
    ]
