# Generated by Django 4.2.9 on 2025-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_alter_electricitytariff_cost_tier1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='municipality_logos', verbose_name='Logo Comune'),
        ),
    ]
