# Generated by Django 4.2.9 on 2025-03-05 21:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_total_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget Totale'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ricavi Attesi Totali'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_roi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-99.99')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='ROI Totale'),
        ),
    ]
