# Generated by Django 5.0.7 on 2025-03-02 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('station_type', models.CharField(choices=[('ac_slow', 'AC Lenta (fino a 7.4 kW)'), ('ac_fast', 'AC Veloce (11-22 kW)'), ('dc_fast', 'DC Veloce (50 kW)'), ('hpc', 'High Power Charger (>100 kW)')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Pianificata'), ('permitting', 'In Fase di Autorizzazione'), ('installing', 'In Installazione'), ('testing', 'In Test'), ('operational', 'Operativa'), ('maintenance', 'In Manutenzione'), ('offline', 'Fuori Servizio'), ('decommissioned', 'Dismessa')], default='planned', max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('connection_cost', models.DecimalField(decimal_places=2, help_text="Costo per l'allaccio", max_digits=10)),
                ('installation_cost', models.DecimalField(decimal_places=2, help_text='Costo di installazione', max_digits=10)),
                ('hardware_cost', models.DecimalField(decimal_places=2, help_text="Costo dell'hardware", max_digits=10)),
                ('design_cost', models.DecimalField(decimal_places=2, help_text='Costo di progettazione', max_digits=10)),
                ('permit_cost', models.DecimalField(decimal_places=2, help_text='Costo dei permessi', max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, help_text='Altri costi', max_digits=10)),
                ('power_kw', models.DecimalField(decimal_places=2, help_text='Potenza in kW', max_digits=8)),
                ('connector_types', models.CharField(help_text='Tipi di connettori separati da virgola', max_length=255)),
                ('num_connectors', models.PositiveIntegerField(default=2)),
                ('grid_connection_capacity', models.DecimalField(decimal_places=2, help_text='Capacità di connessione alla rete in kW', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
                ('area_sqkm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planning', 'In Pianificazione'), ('approval', 'In Approvazione'), ('construction', 'In Costruzione'), ('operational', 'Operativo'), ('maintenance', 'In Manutenzione'), ('closed', 'Chiuso')], default='planning', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_term_years', models.PositiveIntegerField(default=10)),
                ('pre_amortization_years', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cpo_core.organization')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolarInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_kw', models.DecimalField(decimal_places=2, help_text='Capacità in kW', max_digits=8)),
                ('panel_type', models.CharField(max_length=100)),
                ('num_panels', models.PositiveIntegerField()),
                ('installation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_production_kwh', models.DecimalField(decimal_places=2, help_text='Produzione annuale stimata in kWh', max_digits=10)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('charging_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_installation', to='cpo_core.chargingstation')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planning', 'In Pianificazione'), ('permit', 'Richiesta Permessi'), ('approval', 'In Approvazione'), ('construction', 'In Costruzione'), ('operational', 'Operativo'), ('maintenance', 'In Manutenzione'), ('closed', 'Chiuso')], default='planning', max_length=20)),
                ('start_date', models.DateField()),
                ('planned_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='cpo_core.municipality')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='cpo_core.project')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_subprojects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_stations', to='cpo_core.subproject'),
        ),
    ]
