# Generated by Django 5.0.7 on 2025-03-02 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Investimento totale (€)')),
                ('expected_roi', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ROI atteso (%)')),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ROI calcolato (%)')),
                ('payback_period', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Periodo di recupero (anni)')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importo prestito (€)')),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, default=3.5, max_digits=5, verbose_name='Tasso di interesse (%)')),
                ('loan_term', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Durata prestito (anni)')),
                ('grace_period', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Preammortamento (anni)')),
                ('electricity_price_kwh', models.DecimalField(decimal_places=4, default=0.25, max_digits=6, verbose_name='Prezzo elettricità (€/kWh)')),
                ('charging_price_kwh', models.DecimalField(decimal_places=4, default=0.45, max_digits=6, verbose_name='Prezzo ricarica (€/kWh)')),
                ('include_solar', models.BooleanField(default=False, verbose_name='Includere impianto fotovoltaico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpo_financial_projection', to='cpo_core.project')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Anno')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ricavi (€)')),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Spese operative (€)')),
                ('loan_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rata prestito (€)')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costi manutenzione (€)')),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costi elettricità (€)')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Utile netto (€)')),
                ('financial_projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_projections', to='cpo_core.financialprojection')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('financial_projection', 'year')},
            },
        ),
    ]
