# Generated by Django 4.2.9 on 2025-03-05 23:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpo_core', '0002_financialprojection_yearlyprojection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargingstation',
            options={'verbose_name': 'Stazione di Ricarica', 'verbose_name_plural': 'Stazioni di Ricarica'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name', 'province'], 'verbose_name': 'Comune', 'verbose_name_plural': 'Comuni'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organizzazione', 'verbose_name_plural': 'Organizzazioni'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Progetto', 'verbose_name_plural': 'Progetti'},
        ),
        migrations.AlterModelOptions(
            name='solarinstallation',
            options={'verbose_name': 'Impianto Fotovoltaico', 'verbose_name_plural': 'Impianti Fotovoltaici'},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={'verbose_name': 'Sotto-Progetto', 'verbose_name_plural': 'Sotto-Progetti'},
        ),
        migrations.RemoveField(
            model_name='chargingstation',
            name='hardware_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='avg_kwh_session',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6, verbose_name='Media kWh/Sessione'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='charging_price_kwh',
            field=models.DecimalField(decimal_places=4, default=0.45, max_digits=6, verbose_name='Prezzo Ricarica (EUR/kWh)'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='energy_cost_kwh',
            field=models.DecimalField(decimal_places=4, default=0.25, max_digits=6, verbose_name='Costo Energia (EUR/kWh)'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='estimated_sessions_day',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Sessioni Stimate/Giorno'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='has_photovoltaic_system',
            field=models.BooleanField(default=False, verbose_name='Impianto Fotovoltaico'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='identifier',
            field=models.CharField(default='CS-000000', max_length=50, unique=True, verbose_name='Identificatore Stazione'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='photovoltaic_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kWp', max_digits=8, null=True, verbose_name='Capacita Fotovoltaico'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='power_type',
            field=models.CharField(choices=[('ac', 'AC'), ('dc', 'DC'), ('ac_dc', 'AC/DC')], default='ac', max_length=10, verbose_name='Tipo di Potenza'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='station_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Colonnina'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='ev_adoption_rate',
            field=models.FloatField(default=2.0, verbose_name='Tasso di adozione EV (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Effettiva Completamento'),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_completion_date',
            field=models.DateField(default='2025-12-31', verbose_name='Data Prevista Completamento'),
        ),
        migrations.AddField(
            model_name='project',
            name='photovoltaic_integration',
            field=models.BooleanField(default=False, verbose_name='Integrazione Fotovoltaico'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='Italia', max_length=100, verbose_name='Regione'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget Totale'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ricavi Attesi Totali'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_roi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-99.99')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='ROI Totale'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indirizzo'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='charger_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca Colonnina'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='charger_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modello Colonnina'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='civil_works_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Opere Civili'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='connection_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Allaccio Rete'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='connector_types',
            field=models.CharField(blank=True, help_text='Separati da virgola, esempio: Type 2, CCS, CHAdeMO', max_length=255, null=True, verbose_name='Tipi di Connettori'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='equipment_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Colonnina'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ricavi Attesi'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='installation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Installazione'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='latitude_approved',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine Approvata'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='latitude_proposed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine Proposta'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='longitude_approved',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine Approvata'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='longitude_proposed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine Proposta'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='num_connectors',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero Connettori'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='other_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altri Costi'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='permit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Permessi'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Potenza (kW)'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-99.99')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='ROI'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Attivazione'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='connection_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Allaccio'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='connector_types',
            field=models.CharField(default='Type 2', help_text='Separati da virgola', max_length=255, verbose_name='Tipi di Connettori'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='design_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Progettazione'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='grid_connection_capacity',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='kW', max_digits=8, verbose_name='Capacita Connessione Rete'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='installation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Installazione'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Installazione'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Stazione'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='num_connectors',
            field=models.PositiveIntegerField(default=2, verbose_name='Numero Connettori'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Altri Costi'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='permit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Permessi'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='power_kw',
            field=models.DecimalField(decimal_places=2, default=22.0, help_text='kW', max_digits=8, verbose_name='Potenza'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='station_type',
            field=models.CharField(choices=[('ac_slow', 'AC Lenta (fino a 7.4 kW)'), ('ac_fast', 'AC Veloce (11-22 kW)'), ('dc_fast', 'DC Veloce (50 kW)'), ('hpc', 'High Power Charger (>100 kW)')], max_length=20, verbose_name='Tipo Stazione'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='status',
            field=models.CharField(choices=[('planned', 'Pianificata'), ('permitting', 'In Fase di Autorizzazione'), ('ordered', 'Ordinata'), ('installing', 'In Installazione'), ('installed', 'Installata'), ('testing', 'In Test'), ('active', 'Attiva'), ('operational', 'Operativa'), ('maintenance', 'In Manutenzione'), ('offline', 'Fuori Servizio'), ('inactive', 'Inattiva'), ('decommissioned', 'Dismessa')], default='planned', max_length=20, verbose_name='Stato Stazione'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_stations', to='cpo_core.subproject', verbose_name='Sotto-Progetto'),
        ),
        migrations.AlterField(
            model_name='financialprojection',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_projection_core', to='cpo_core.project'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='area_sqkm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area (km quadri)'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Contatto'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Contatto'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono Contatto'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Comune'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Popolazione'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='province',
            field=models.CharField(max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Regione'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Email di contatto'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(max_length=20, verbose_name='Telefono di contatto'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codice Fiscale/P.IVA'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='project',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importo Prestito'),
        ),
        migrations.AlterField(
            model_name='project',
            name='loan_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasso di Interesse'),
        ),
        migrations.AlterField(
            model_name='project',
            name='loan_term_years',
            field=models.PositiveIntegerField(default=10, verbose_name='Durata Prestito (anni)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Progetto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cpo_core.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pre_amortization_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Anni di Preammortamento'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2023-01-01', verbose_name='Data Inizio Progetto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Pianificazione'), ('approval', 'In Approvazione'), ('in_progress', 'In Corso'), ('construction', 'In Costruzione'), ('operational', 'Operativo'), ('maintenance', 'In Manutenzione'), ('completed', 'Completato'), ('suspended', 'Sospeso'), ('closed', 'Chiuso')], default='planning', max_length=20, verbose_name='Stato Progetto'),
        ),
        migrations.AlterField(
            model_name='solarinstallation',
            name='annual_production_kwh',
            field=models.DecimalField(decimal_places=2, help_text='kWh', max_digits=10, verbose_name='Produzione Annuale Stimata'),
        ),
        migrations.AlterField(
            model_name='solarinstallation',
            name='capacity_kw',
            field=models.DecimalField(decimal_places=2, help_text='kWp', max_digits=8, verbose_name='Capacita'),
        ),
        migrations.AlterField(
            model_name='solarinstallation',
            name='installation_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Installazione'),
        ),
        migrations.AlterField(
            model_name='solarinstallation',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Installazione'),
        ),
        migrations.AlterField(
            model_name='solarinstallation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='solarinstallation',
            name='num_panels',
            field=models.PositiveIntegerField(verbose_name='Numero Pannelli'),
        ),
        migrations.AlterField(
            model_name='solarinstallation',
            name='panel_type',
            field=models.CharField(max_length=100, verbose_name='Tipo Pannelli'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Effettiva Completamento'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budget Totale'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='cpo_core.municipality', verbose_name='Comune'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Sottoprogetto'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='planned_completion_date',
            field=models.DateField(default='2023-12-31', verbose_name='Data Prevista Completamento'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='cpo_core.project', verbose_name='Progetto Principale'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_subprojects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='start_date',
            field=models.DateField(default='2023-01-01', verbose_name='Data Inizio'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='status',
            field=models.CharField(choices=[('planning', 'Pianificazione'), ('permit', 'Richiesta Permessi'), ('approval', 'In Approvazione'), ('construction', 'In Costruzione'), ('in_progress', 'In Corso'), ('operational', 'Operativo'), ('maintenance', 'In Manutenzione'), ('completed', 'Completato'), ('suspended', 'Sospeso'), ('closed', 'Chiuso')], default='planning', max_length=20, verbose_name='Stato Sotto-Progetto'),
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together={('name', 'province')},
        ),
    ]
