# Generated by Django 4.2.9 on 2025-03-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_alter_electricitytariff_cost_tier1_and_more'),
        ('cpo_core', '0004_transfer_municipalities_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='cadastral_data',
            field=models.CharField(blank=True, help_text='Foglio, Particella, Subalterno', max_length=255, null=True, verbose_name='Dati Catastali'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='num_chargers',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero Colonnine'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='power_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Potenza Richiesta a E-Distribuzione (kW)'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='usage_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_stations', to='infrastructure.stationusageprofile', verbose_name='Profilo di Consumo'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='use_project_completion_date',
            field=models.BooleanField(default=False, verbose_name='Usa Data Completamento Progetto'),
        ),
        migrations.CreateModel(
            name='StationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='charging_stations/')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('is_before_installation', models.BooleanField(default=True, verbose_name="Prima dell'installazione")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cpo_core.subproject')),
            ],
            options={
                'verbose_name': 'Immagine Stazione',
                'verbose_name_plural': 'Immagini Stazioni',
            },
        ),
    ]
