# Generated by Django 4.2.9 on 2025-03-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpo_core', '0005_subproject_cadastral_data_subproject_num_chargers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Codice colonnina')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modello')),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Potenza (kW)')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero seriale')),
                ('num_connectors', models.PositiveIntegerField(default=1, verbose_name='Numero Connettori')),
                ('connector_types', models.CharField(blank=True, help_text='Separati da virgola, esempio: Type 2, CCS, CHAdeMO', max_length=255, null=True, verbose_name='Tipi di Connettori')),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Costo d'acquisto (€)")),
                ('installation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Costo d'installazione (€)")),
                ('status', models.CharField(choices=[('operational', 'Operativa'), ('maintenance', 'In Manutenzione'), ('offline', 'Non Operativa'), ('planned', 'Pianificata'), ('installing', 'In Installazione')], default='planned', max_length=20, verbose_name='Stato')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Data installazione')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Data attivazione')),
                ('is_fast_charging', models.BooleanField(default=False, verbose_name='Ricarica rapida')),
                ('is_smart_charging', models.BooleanField(default=False, verbose_name='Smart charging')),
                ('has_display', models.BooleanField(default=True, verbose_name='Display')),
                ('has_rfid', models.BooleanField(default=True, verbose_name='Lettore RFID')),
                ('has_app_control', models.BooleanField(default=True, verbose_name='Controllo da app')),
                ('has_load_balancing', models.BooleanField(default=False, verbose_name='Load balancing')),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='cpo_core.subproject')),
            ],
            options={
                'verbose_name': 'Colonnina',
                'verbose_name_plural': 'Colonnine',
                'ordering': ['subproject', 'code'],
            },
        ),
    ]
