# Generated by Django 4.2.9 on 2025-03-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpo_core', '0006_charger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charger',
            options={'ordering': ['code'], 'verbose_name': 'Colonnina', 'verbose_name_plural': 'Colonnine'},
        ),
        migrations.AddField(
            model_name='charger',
            name='charging_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='cpo_core.chargingstation'),
        ),
        migrations.AlterField(
            model_name='charger',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='cpo_core.subproject'),
        ),
    ]
