# Generated by Django 4.2.9 on 2025-03-07 09:27

import cpo_core.models.municipality
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo_core', '0009_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=cpo_core.models.municipality.municipality_logo_path, verbose_name='Logo Comune'),
        ),
    ]
