# Generated by Django 4.2.9 on 2025-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo_core', '0011_municipality_latitude_municipality_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='ground_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Area Occupata (m²)'),
        ),
    ]
