# Generated by Django 4.2.9 on 2025-03-08 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpo_core', '0012_subproject_ground_area_sqm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='charging_stations/photos/', verbose_name='Foto')),
                ('phase', models.CharField(choices=[('pre_installation', "Prima dell'installazione"), ('during_installation', "Durante l'installazione"), ('post_installation', "Dopo l'installazione")], max_length=20, verbose_name='Fase')),
                ('title', models.CharField(max_length=100, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('date_taken', models.DateField(blank=True, null=True, verbose_name='Data Scatto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cpo_core.chargingstation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_station_photos', to=settings.AUTH_USER_MODEL, verbose_name='Caricata da')),
            ],
            options={
                'verbose_name': 'Foto Stazione di Ricarica',
                'verbose_name_plural': 'Foto Stazioni di Ricarica',
                'ordering': ['-date_taken', '-created_at'],
            },
        ),
    ]
