# Generated by Django 4.2.9 on 2025-03-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpo_core', '0013_chargingstationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstationphoto',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cpo_core.subproject'),
        ),
        migrations.AlterField(
            model_name='chargingstationphoto',
            name='charging_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cpo_core.chargingstation'),
        ),
    ]
