# Generated by Django 4.2.9 on 2025-03-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo_core', '0014_chargingstationphoto_subproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='local_festival_days',
            field=models.IntegerField(blank=True, default=0, help_text="Numero di giorni all'anno in cui la stazione non è disponibile per feste locali", null=True, verbose_name="Giorni festa paesana all'anno"),
        ),
        migrations.AddField(
            model_name='subproject',
            name='weekly_market_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], help_text='Giorno della settimana in cui si tiene il mercato e la stazione non è disponibile', null=True, verbose_name='Giorno del mercato settimanale'),
        ),
    ]
