# Generated by Django 4.2.9 on 2025-03-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo_core', '0015_subproject_local_festival_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='rainy_days',
            field=models.PositiveSmallIntegerField(default=0, help_text="Giorni di pioggia stimati che riducono l'utilizzo delle colonnine del 30%", verbose_name='Giorni di Pioggia Previsti/Anno'),
        ),
    ]
