# Generated by Django 4.2.9 on 2025-03-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regione'),
        ),
    ]
